FROM node:latest as builder

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build --prod

CMD ["npm", "start"]

#FROM nginx:alpine
#COPY src/nginx/etc/conf.d/default.confg /etc/nginx/conf.d/default.conf
#COPY --from=builder /app/dist/obligatoriobdd1 /usr/share/nginx/html